### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by nicosomb** [milanaleksic/wallabago#3]
Hello @milanaleksic! 

Thank you for this tool.

Can you provide documentation about your project please? 

Nicolas

**Comment by milanaleksic** [comment]
Progress on this project will be quite slow (no real big time investment planned).

At this time it just sits in front of wallabag as a simple proxy:
- it keeps the session cookies internally, so if I use my cellphone and change from wifi to 3G I don't have to re-login;
- everything is just routed through (to allow iOS application to continue working for example).
- only my own forked wallabag is going to be supported which is old (https://github.com/milanaleksic/wallabag)

I have no idea where I am going with this, it might be a source of some ideas you can take upstream @nicosomb , but it's meant only for my own practice - do not plan on productizing it or making a site for it, I will be no competition, don't worry ;) If it comes to that point that it endangers wallabag, I will just move it to a private repo

**Comment by milanaleksic** [comment]
@Nicosomb: I have updated the README pointing to installation instructions and description about what the app really does; I will close this issue since I plan on updating the docs in the future when I add new features and will use issues to track my pending and ongoing ideas when they appear

**Comment by nicosomb** [comment]
Thank you 👍
